### ISSUE TITLE
Wordpress Multisite

### ISSUE THREAD

**Issue by austinvernsonger** [Perfit-labs/Issues#1]
I have multiple subsites part of my multisite installation

- 138.197.14.4
- perfit.co
- austinsonger.com
- austinsonger.me
- isaacsonger.us
- danabujalski.com

and for some reason only austinsonger.com is working....

[Screenshot](https://farm6.staticflickr.com/5509/32151056326_a23ec8c7e5.jpg)

The other ones were working, but not anymore.

**Comment by jaswalanita53** [comment]
I can't see the code, so form where i can use code for local setup.

**Comment by austinvernsonger** [comment]
What code you talking about?

**Comment by jaswalanita53** [comment]
Hello Austin,

Can you please schedule a meeting so that we can move further. I am make
sure everything before start.

Thanks
Anita

**Comment by chhrahul** [comment]
Hi Austin,

Actually, now I have the details of ssh working and I understand the task and starting work on it.

I will keep you updated on the progress. I will make an akeeba backup before I start work today.

Thanks
Anita

**Comment by jaswalanita53** [comment]
Hi Austin,

Actually, now I have the details of ssh working and I understand the task and starting work on it.

I will keep you updated on the progress. I will make an akeeba backup before I start work today.

Thanks
Anita

**Comment by austinvernsonger** [comment]
What was wrong with it?

**Comment by austinvernsonger** [comment]
And for some reason I can no longer log in.

**Comment by jaswalanita53** [comment]
Hi Austin

The issue was with the php version of our server, seems like there was an update made on php version of the server recently and some of coding functions in the plugin were not compatible with latest php version.

You can login with the username austinvernsonger and password is austin@123

There are some links in admin which are going to an ip and which are giving us broken pages and I am working on resolving the issue.

Thanks
Anita

**Comment by jaswalanita53** [comment]
Hi Austin

The task of multi-websites is completed. Now all the websites sub-domain and main domains are working fine in admin. 

You can go ahead and test everything and let me know if anything doesn't work.

Also, You can assign me more tasks on the website. I see there is a lot to be done on the theme and functionality of the website, so you can assign me those tasks as well.

Thanks
Anita

**Comment by austinvernsonger** [comment]
I can't log in again.

**Comment by austinvernsonger** [comment]
It also doesn't send me a password when try to reset. I could do it through the database, but I also can't access the database.

**Comment by jaswalanita53** [comment]
Hi Austin

I shall check this in the morning and will get back to you.

Thanks 
Anita

**Comment by austinvernsonger** [comment]
Okay.

**Comment by jaswalanita53** [comment]
Hi Austin

I have checked that there is some problem with sending emails on our server. I tried a simple php script on our website to send a sample email and it doesn't work. The same script works on my server and sends an email. So there is definitely a problem with email server of our website. Please get in touch with server support to get this resolved.

Following are admin login details:
http://austinsonger.com/wp-admin
user: austinvernsonger
pswd: admin@123

Thanks
Anita

**Comment by austinvernsonger** [comment]
@jaswalanita53 it's a digitalocean droplet.

**Comment by jaswalanita53** [comment]
Hi Austin

Please assign me more tasks.

Thanks
Anita
